# Generated by Django 5.2.3 on 2025-07-06 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=10, unique=True)),
                ('hardware_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('camera', 'Camera'), ('lidar', 'Lidar'), ('imu', 'IMU'), ('sonar', 'Sonar')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('specification', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('coefficients', models.JSONField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='missions.sensor')),
            ],
        ),
    ]
