# Generated by Django 5.2.3 on 2025-07-06 18:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(choices=[('pillar', 'Pillar'), ('wall', 'Wall')], default='wall', max_length=8)),
                ('max_depth', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='calibration',
            name='coefficients',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='calibration',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('sensor',), name='one_active_calibration_per_sensor'),
        ),
        migrations.AddField(
            model_name='mission',
            name='rover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='missions.rover'),
        ),
        migrations.AddField(
            model_name='sensordeployment',
            name='calibration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='missions.calibration'),
        ),
        migrations.AddField(
            model_name='sensordeployment',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='sensordeployment',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='missions.sensor'),
        ),
        migrations.AddIndex(
            model_name='mission',
            index=models.Index(fields=['start_time'], name='missions_mi_start_t_f80204_idx'),
        ),
    ]
