# Generated by Django 5.2.3 on 2025-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_sensordeployment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('camera', 'Camera'), ('lidar', 'Lidar'), ('imu', 'IMU'), ('pressure', 'Pressure'), ('sonar', 'Sonar')], max_length=20),
        ),
    ]
