# Generated by Django 5.2.4 on 2025-07-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='target_type',
            field=models.CharField(choices=[('pillar', 'Pillar'), ('wall', 'Wall')], default='wall', max_length=12),
        ),
    ]
