# Generated by Django 5.2.4 on 2025-07-12 16:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_mission_target_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tlog_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('depth_m', models.FloatField(blank=True, null=True)),
                ('roll_deg', models.FloatField(blank=True, null=True)),
                ('pitch_deg', models.FloatField(blank=True, null=True)),
                ('yaw_deg', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['mission', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoverHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('hardware_config', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AlterModelOptions(
            name='calibration',
            options={'ordering': ['-effective_from']},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='calibration',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibrations', to='missions.sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('camera', 'Camera'), ('compass', 'Compass'), ('imu', 'IMU'), ('pressure', 'Pressure'), ('sonar', 'Sonar')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='sensordeployment',
            index=models.Index(fields=['mission'], name='missions_se_mission_978a07_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordeployment',
            index=models.Index(fields=['sensor'], name='missions_se_sensor__c8bb3b_idx'),
        ),
        migrations.AddField(
            model_name='logfile',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_files', to='missions.mission'),
        ),
        migrations.AddField(
            model_name='navsample',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_samples', to='missions.mission'),
        ),
        migrations.AddConstraint(
            model_name='roverhardware',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('name',), name='unique_active_roverhardware_per_name'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='rover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='missions.roverhardware'),
        ),
        migrations.AddIndex(
            model_name='logfile',
            index=models.Index(fields=['mission'], name='missions_lo_mission_b782d0_idx'),
        ),
        migrations.AddIndex(
            model_name='logfile',
            index=models.Index(fields=['created_at'], name='missions_lo_created_e61f59_idx'),
        ),
        migrations.AddIndex(
            model_name='navsample',
            index=models.Index(fields=['mission', 'timestamp'], name='missions_na_mission_7baca5_idx'),
        ),
        migrations.AddIndex(
            model_name='navsample',
            index=models.Index(fields=['yaw_deg'], name='missions_na_yaw_deg_933491_idx'),
        ),
        migrations.DeleteModel(
            name='Rover',
        ),
    ]
