# Generated by Django 5.2.4 on 2025-07-13 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_logfile_navsample_roverhardware_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_number', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('servo_pitch_deg', models.FloatField(blank=True, null=True)),
                ('nav_match_time_diff_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['media_asset', 'frame_number'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=6)),
                ('file_path', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('file_metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='navsample',
            name='missions_na_yaw_deg_933491_idx',
        ),
        migrations.AlterField(
            model_name='navsample',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='navsample',
            index=models.Index(fields=['depth_m'], name='missions_na_depth_m_b24ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='navsample',
            index=models.Index(fields=['depth_m', 'yaw_deg'], name='missions_na_depth_m_4a79ef_idx'),
        ),
        migrations.AddField(
            model_name='frameindex',
            name='closest_nav_sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='frames', to='missions.navsample'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='missions.sensordeployment'),
        ),
        migrations.AddField(
            model_name='frameindex',
            name='media_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='missions.mediaasset'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['start_time'], name='missions_me_start_t_6f6b64_idx'),
        ),
        migrations.AddIndex(
            model_name='frameindex',
            index=models.Index(fields=['timestamp'], name='missions_fr_timesta_10ac24_idx'),
        ),
    ]
