# Generated by Django 5.2.4 on 2025-07-13 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_frameindex_mediaasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImuSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('gx_rad_s', models.FloatField()),
                ('gy_rad_s', models.FloatField()),
                ('gz_rad_s', models.FloatField()),
                ('ax_m_s2', models.FloatField()),
                ('ay_m_s2', models.FloatField()),
                ('az_m_s2', models.FloatField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_samples', to='missions.sensordeployment')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_samples', to='missions.logfile')),
            ],
            options={
                'ordering': ['log_file', 'timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['log_file', 'timestamp'], name='missions_im_log_fil_7eaf5f_idx'), models.Index(fields=['deployment', 'timestamp'], name='missions_im_deploym_10c362_idx')],
            },
        ),
        migrations.CreateModel(
            name='MagnetometerSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('mx_uT', models.FloatField()),
                ('my_uT', models.FloatField()),
                ('mz_uT', models.FloatField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_samples', to='missions.sensordeployment')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_samples', to='missions.logfile')),
            ],
            options={
                'ordering': ['log_file', 'timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['log_file', 'timestamp'], name='missions_ma_log_fil_67cc77_idx'), models.Index(fields=['deployment', 'timestamp'], name='missions_ma_deploym_470986_idx')],
            },
        ),
        migrations.CreateModel(
            name='PressureSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('pressure_pa', models.FloatField()),
                ('temperature_C', models.FloatField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_samples', to='missions.sensordeployment')),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_samples', to='missions.logfile')),
            ],
            options={
                'ordering': ['log_file', 'timestamp'],
                'abstract': False,
                'indexes': [models.Index(fields=['log_file', 'timestamp'], name='missions_pr_log_fil_f48288_idx'), models.Index(fields=['deployment', 'timestamp'], name='missions_pr_deploym_ab20c6_idx')],
            },
        ),
    ]
