# Generated by Django 5.2.4 on 2025-07-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_alter_imusample_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MagnetometerSample',
            new_name='CompassSample',
        ),
        migrations.RenameIndex(
            model_name='compasssample',
            new_name='missions_co_deploym_608f95_idx',
            old_name='missions_ma_deploym_470986_idx',
        ),
    ]
