# Generated by Django 5.2.4 on 2025-07-13 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_rename_magnetometersample_compasssample_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
