# Generated by Django 5.2.4 on 2025-07-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0011_alter_mediaasset_fps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaasset',
            name='fps',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
