# Generated by Django 5.2.4 on 2025-07-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_alter_mediaasset_fps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='description',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='mission',
            name='cloud_cover',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Cloud cover level: low, medium, or high', max_length=6),
        ),
        migrations.AddField(
            model_name='mission',
            name='tide_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Tide level: low, medium, or high', max_length=6),
        ),
        migrations.AddField(
            model_name='mission',
            name='visibility',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Visibility quality: low, medium, or high', max_length=6),
        ),
    ]
