# Generated by Django 5.2.4 on 2025-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0014_rename_description_logfile_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordeployment',
            name='instance',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=0, help_text='Sensor type instance number (0 or 1 only).'),
        ),
    ]
