# Generated by Django 5.2.4 on 2025-07-16 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0015_sensordeployment_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compasssample',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='missions.sensordeployment'),
        ),
        migrations.AlterField(
            model_name='imusample',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='missions.sensordeployment'),
        ),
        migrations.AlterField(
            model_name='pressuresample',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='missions.sensordeployment'),
        ),
        migrations.AddConstraint(
            model_name='sensordeployment',
            constraint=models.UniqueConstraint(fields=('mission', 'sensor', 'instance'), name='unique_sensor_instance_per_mission'),
        ),
    ]
